services:
  filament-system-settings-nginx:
    container_name: filament-system-settings-nginx
    image: filament-system-settings-nginx
    volumes:
      - ../:/home/wwwroot/filament-system-settings
      - ./php/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /home/php/extension:/root/.vscode-server/extensions
      - /home/php/extension-insiders:/root/.vscode-server-insiders/extensions
    build:
      context: .
      dockerfile: ./php/dev.Dockerfile
    ports:
      - 31281:80
      - 31286:31286
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M
    networks:
      filament-system-settings-net:
        ipv4_address: 172.16.128.11

networks:
  filament-system-settings-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.128.0/24
